# Generated by quarto-emit.
# Source: notebooks/pipeline/20_page-execute-pipeline.qmd
# Do not edit directly unless you intend to stop using this document as the source of truth.

library(targets)
library(tarchetypes)

tar_option_set(
  packages = c(
    "duckplyr", "tibble", "here", "readr", "cli", "glue", "purrr", "stringr", "dplyr"
  )
)

list(
  tarchetypes::tar_tangle(
    "notebooks/pipeline/16_page-stage-inputs.qmd"
  ),
  tarchetypes::tar_tangle(
    "notebooks/pipeline/18_page-prep-w3.qmd"
  ),
  tar_target(
    clinic_raw_data_RMA_W3_csv_path,
    pipeline_raw_input_files_paths %>%
      str_subset("RMA_W3_FULL")
  ),
  tar_target(
    clinic_raw_data_RMA_W3_within_file_group_max_df,
    process_csv_safely(
      clinic_raw_data_RMA_W3_csv_path,
      file.path(
        "data/intermediates/RMA_W3",
        paste0(tar_name(), ".parquet")
      )
    ),
    pattern = map(clinic_raw_data_RMA_W3_csv_path),
    format = "file"
  )#,
  #tar_target(
  #  clinic_RMA_W3_group_max_df,
  #  summarise_group_max(clinic_raw_data_RMA_W3_within_file_group_max_df),
  #  memory = "transient"
  #)
)
