project:
  type: book
  output-dir: ../docs

book:
  title: "Madagascar Healthshed-Clinic Data Processing"
  author: "Tinshe M. Tapera"
  date: "8/27/2026"
  chapters:
    - index.qmd
    - 00_cover.qmd

      #bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

extensions:
  - quarto-manual


